# Generated by Django 5.1.4 on 2024-12-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profileimg",
            new_name="profile",
        ),
    ]
